# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  only:
    - master

# language
language: c

# Environment variables
env:
  global:
    - GH_REPO_NAME: mergesort-concurrent
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxygen
    - GH_REPO_REF: github.com/yangyang95/mergesort-concurrent.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - make
  - ./generateDocumentationAndDeploy.sh

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh